services:
  ollama:
    image: docker.io/ollama/ollama:0.5.12
    volumes:
      - ollama.volume:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ollama --version || exit 1
      interval: 60s

  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.5.16
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - Environment=OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_started
        restart: true

volumes:
  ollama: {}
  open-webui: {}
